<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="icon" href="{{ asset('logo.jpg') }}" type="image/jpeg">
  <title>Presensi Murid - SMP Muhammadiyah 44</title>
  <link rel="stylesheet" href="{{ asset('guru css/presensimurid.css') }}?v=1">
</head>
<body>
<div class="page-loader" id="pageLoader"><div class="loader-logo-wrap"><div class="loader-spinner"></div><div class="loader-logo"><img src="{{ asset('logo.jpg') }}" alt="Logo sekolah"></div></div><div class="loader-text">SMP Muhammadiyah 44</div><div class="loader-subtext">Memuat presensi murid...</div></div>
<div class="guru-page" id="guruPage">
  <aside class="sidebar" id="sidebar"><div class="sidebar-header"><div class="sidebar-brand"><div class="sidebar-logo"><img src="{{ asset('logo.jpg') }}" alt="Logo sekolah"></div><div><div class="sidebar-title">SMP Muhammadiyah 44</div><div class="sidebar-subtitle">Portal Guru</div></div></div><button class="sidebar-close-btn" onclick="toggleSidebar()">✕</button></div><div class="sidebar-section-label">Menu</div><nav class="sidebar-nav">
    <a class="nav-item" style="--delay:1" href="{{ route('guru.dashboard') }}"><span class="nav-icon-box">🏠</span>Dashboard</a><a class="nav-item" style="--delay:2" href="{{ route('guru.presensi-guru') }}"><span class="nav-icon-box">🧾</span>Presensi Guru</a><a class="nav-item" style="--delay:3" href="{{ route('guru.jadwal') }}"><span class="nav-icon-box">📅</span>Jadwal Mengajar</a><a class="nav-item active" style="--delay:4" href="{{ route('guru.presensi-murid') }}"><span class="nav-icon-box">👥</span>Presensi Murid</a><a class="nav-item" style="--delay:5" href="{{ route('guru.riwayat-presensi') }}"><span class="nav-icon-box">🕘</span>Riwayat Presensi</a><a class="nav-item" style="--delay:6" href="{{ route('guru.profil') }}"><span class="nav-icon-box">👤</span>Profil</a>
  </nav><div class="sidebar-footer"><div class="sidebar-footer-user"><div class="avatar">AF</div><div><div class="name">Ust. Ahmad Fauzi</div><div class="role">Guru Mata Pelajaran</div></div></div><form action="{{ route('guru.logout') }}" method="POST">@csrf<button class="nav-item logout-item" type="submit"><span class="nav-icon-box">🚪</span>Keluar</button></form></div></aside><div class="sidebar-overlay" id="sidebarOverlay" onclick="toggleSidebar()"></div>
  <header class="topbar"><div class="topbar-left"><button class="burger-btn" id="burgerBtn" onclick="toggleSidebar()"><span></span><span></span><span></span></button><div class="brand-wrap"><span class="brand-dot"></span><span class="portal-tag">Portal Guru • SMP Muhammadiyah 44</span></div></div><div class="topbar-right"><div class="date-pill" id="liveDatetime">Memuat waktu...</div><div class="bell-btn">🔔<span class="badge"></span></div><div class="profile-pill"><div class="avatar">AF</div><div class="profile-meta"><div class="name">Ust. Ahmad Fauzi, S.Pd.</div><div class="role">Guru IPA &amp; Matematika</div></div></div></div></header>
  <main class="content">
    <div class="page-header"><div><h1>Presensi Murid</h1><p>Kelola sesi mengajar dan kehadiran kelas hari ini.</p></div><span class="term-chip">{{ now()->locale('id')->translatedFormat('l, j F Y') }}</span></div>
    @if(session('success'))<div class="panel" role="status">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="panel" role="alert">{{ $errors->first() }}</div>@endif
    <section class="panel" style="margin-bottom:20px">
      <div class="panel-head"><div class="panel-title">Jadwal Mengajar Hari Ini</div><span class="muted">{{ $jadwals->count() }} jadwal dari database</span></div>
      <div class="table-wrap"><table class="data-table"><thead><tr><th>Jam</th><th>Mata Pelajaran</th><th>Kelas</th><th>Status Sesi</th><th>Aksi</th></tr></thead><tbody>
        @forelse($jadwals as $jadwal)
          @php($jadwalSesi = $jadwal->sesiPelajarans->first())
          <tr><td>{{ substr($jadwal->jam_mulai, 0, 5) }}-{{ substr($jadwal->jam_selesai, 0, 5) }}</td><td>{{ $jadwal->mapel->nama_mapel }}</td><td>{{ $jadwal->kelas->nama_kelas }}</td><td>{{ $jadwalSesi?->status_sesi ?? 'Belum' }}</td><td>
            @if($jadwalSesi?->status_sesi === 'Berlangsung')<a class="btn btn-primary" href="{{ route('guru.presensi-murid', ['sesi' => $jadwalSesi->id]) }}">Kelola Sesi</a>
            @elseif($jadwalSesi?->status_sesi !== 'Selesai')<button class="btn btn-primary open-session" data-url="{{ route('guru.sesi.open', ['jadwal' => $jadwal->id]) }}">Buka Sesi</button>
            @else<span class="muted">Selesai</span>@endif
          </td></tr>
        @empty<tr><td colspan="5">Tidak ada jadwal mengajar untuk hari ini.</td></tr>@endforelse
      </tbody></table></div>
    </section>
    <section class="qr-layout" id="sessionPanel" data-session-id="{{ $sesi?->id }}" data-status-url="{{ $sesi ? route('guru.sesi.status', ['sesi' => $sesi->id]) : '' }}" data-qr-template="{{ route('guru.sesi.qr', ['sesi' => '__ID__']) }}" data-close-template="{{ route('guru.sesi.close', ['sesi' => '__ID__']) }}" data-manual-template="{{ route('guru.presensi-murid.update', ['presensi' => '__ID__']) }}" data-qr-expires-at="{{ $sesi?->qr_expires_at?->toIso8601String() }}">
      <div class="panel qr-panel"><div class="panel-head"><div class="panel-title">QR Code Sesi</div><span class="status-pill hadir" id="sessionStatus">{{ $sesi?->status_sesi ?? 'Belum ada sesi' }}</span></div>
        <div class="qr-box" id="qrBox"><div class="qr-visual {{ $sesi?->qr_expires_at?->isPast() ? 'is-expired' : '' }}" id="qrVisual">
          <div class="qr-image" id="qrImage">@if($sesi?->status_sesi === 'Berlangsung' && $sesi->qr_token && $sesi->qr_expires_at?->isFuture()){!! \SimpleSoftwareIO\QrCode\Facades\QrCode::format('svg')->size(360)->margin(2)->generate($sesi->qr_token) !!}@endif</div>
          <div class="qr-expired-overlay" id="qrExpiredOverlay" {{ $sesi?->qr_expires_at?->isPast() || ! $sesi ? '' : 'hidden' }}>QR Kadaluarsa</div>
        </div>
          <strong id="sessionTitle">{{ $sesi ? $sesi->jadwal->mapel->nama_mapel.' • '.$sesi->jadwal->kelas->nama_kelas : 'Pilih jadwal untuk memulai sesi' }}</strong>
          <span class="qr-countdown" id="qrCountdown" role="timer" aria-live="polite">QR belum aktif</span>
          <small id="qrExpiry">{{ $sesi?->qr_expires_at?->format('H:i:s') ?? 'QR akan berlaku 5 menit' }}</small>
        </div>
        <div class="qr-actions"><div class="attendance-tally" id="attendanceCounts" aria-live="polite">Belum ada sesi aktif</div><div class="session-buttons"><button class="btn btn-primary refresh-qr" id="refreshQr" type="button" {{ $sesi?->status_sesi === 'Berlangsung' ? '' : 'disabled' }}>🔄 Perbarui QR Code (5 Menit)</button><button class="btn btn-close-session" id="closeSession" type="button" {{ $sesi?->status_sesi === 'Berlangsung' ? '' : 'disabled' }}>⛔ Tutup Sesi &amp; Simpan</button></div></div>
      </div>
      <div class="panel"><div class="panel-head"><div class="panel-title">Daftar Presensi Murid</div><span class="muted" id="syncStatus">Menunggu sesi dimulai</span></div><div class="student-grid" id="studentList"><p class="empty-attendance">Buka sesi untuk menampilkan daftar murid.</p></div></div>
    </section>
    <div id="feedback" role="status" aria-live="polite"></div>
    <footer class="footer"><span>Sistem Presensi &amp; Manajemen Akademik SMP Muhammadiyah 44 Tangerang Selatan</span><span>© {{ date('Y') }} SMP Muhammadiyah 44 Tangerang Selatan</span></footer>
  </main>
</div>
<dialog class="session-confirm" id="closeConfirm" aria-labelledby="closeConfirmTitle"><div class="confirm-content"><span class="confirm-icon">!</span><h2 id="closeConfirmTitle">Tutup sesi presensi?</h2><p>Apakah Anda yakin ingin menutup sesi? Siswa yang belum absen akan otomatis tercatat <strong>ALFA</strong>.</p><div class="confirm-actions"><button class="btn" id="cancelClose" type="button">Kembali</button><button class="btn btn-close-session" id="confirmClose" type="button">Ya, Tutup Sesi &amp; Simpan</button></div></div></dialog>
<script>
window.addEventListener('load',()=>setTimeout(()=>{pageLoader.classList.add('hide');guruPage.classList.add('loaded')},500));
function toggleSidebar(){sidebar.classList.toggle('open');sidebarOverlay.classList.toggle('show');burgerBtn.classList.toggle('active')}
function updateLiveDatetime(){const n=new Date(),d=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'],m=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],p=x=>String(x).padStart(2,'0');liveDatetime.textContent=`${d[n.getDay()]}, ${n.getDate()} ${m[n.getMonth()]} ${n.getFullYear()} | ${p(n.getHours())}:${p(n.getMinutes())}:${p(n.getSeconds())} WIB`}
updateLiveDatetime();setInterval(updateLiveDatetime,1000);
const panel=document.getElementById('sessionPanel'),feedback=document.getElementById('feedback'),csrf=document.querySelector('meta[name="csrf-token"]')?.content,closeConfirm=document.getElementById('closeConfirm');
let lastRowsFingerprint='',pollingTimer=null,expiryTimer=null;
async function requestJson(url,method='GET',body=null){const response=await fetch(url,{method,headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.message||Object.values(data.errors||{}).flat()[0]||'Permintaan gagal.');return data}
function showError(error){feedback.className='feedback-message is-error';feedback.textContent=error.message}
function showSuccess(message){feedback.className='feedback-message is-success';feedback.textContent=message}
function renderStudents(rows){const fingerprint=JSON.stringify(rows);if(fingerprint===lastRowsFingerprint)return;lastRowsFingerprint=fingerprint;const list=document.getElementById('studentList');list.replaceChildren();const counts={Hadir:0,Izin:0,Sakit:0,Alfa:0,'Belum Absen':0};rows.forEach(row=>{counts[row.status]=(counts[row.status]||0)+1;const line=document.createElement('div');line.className=`student-row${row.status==='Hadir'?' is-hadir':''}`;line.innerHTML='<div><span class="student-name"></span><span class="student-id"></span></div><div class="radio-group"></div>';line.querySelector('.student-name').textContent=row.nama;line.querySelector('.student-id').textContent=row.nisn;const radios=line.querySelector('.radio-group');['Hadir','Izin','Sakit','Alfa'].forEach(status=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name=`status-${row.id}`;input.value=status;input.checked=row.status===status;input.disabled=document.getElementById('sessionStatus').textContent!=='Berlangsung';input.addEventListener('change',async()=>{try{await requestJson(panel.dataset.manualTemplate.replace('__ID__',row.id),'PUT',{status});lastRowsFingerprint='';await refreshStatus();showSuccess('Status presensi tersimpan.')}catch(error){showError(error)}});label.append(input,document.createTextNode(` ${status}`));radios.append(label)});list.append(line)});document.getElementById('attendanceCounts').textContent=`Hadir ${counts.Hadir||0} dari ${rows.length} murid • Izin ${counts.Izin||0} • Sakit ${counts.Sakit||0} • Alfa ${counts.Alfa||0} • Belum ${counts['Belum Absen']||0}`}
function setExpiry(value){panel.dataset.qrExpiresAt=value||'';document.getElementById('qrExpiry').textContent=value?`Berlaku sampai ${new Date(value).toLocaleTimeString('id-ID')}`:'QR tidak aktif';updateCountdown()}
function updateCountdown(){const expiry=Date.parse(panel.dataset.qrExpiresAt||'');const seconds=Math.ceil((expiry-Date.now())/1000);const expired=!Number.isFinite(expiry)||seconds<=0;const visual=document.getElementById('qrVisual'),overlay=document.getElementById('qrExpiredOverlay'),refresh=document.getElementById('refreshQr'),countdown=document.getElementById('qrCountdown');visual.classList.toggle('is-expired',expired);overlay.hidden=!expired||document.getElementById('sessionStatus').textContent!=='Berlangsung';if(expired){countdown.textContent='QR Kadaluarsa';refresh.classList.add('needs-refresh')}else{countdown.textContent=`QR Aktif: ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;refresh.classList.remove('needs-refresh')}}
function updateState(data){document.getElementById('sessionStatus').textContent=data.status_sesi;document.getElementById('refreshQr').disabled=data.status_sesi!=='Berlangsung';document.getElementById('closeSession').disabled=data.status_sesi!=='Berlangsung';document.getElementById('syncStatus').textContent=data.status_sesi==='Berlangsung'?'Pembaruan otomatis setiap 3 detik':data.status_sesi; if(data.qr_expires_at!==undefined)setExpiry(data.qr_expires_at);renderStudents(data.presensi||[]);updateCountdown()}
function showQr(data){document.getElementById('qrImage').innerHTML=data.qr_svg;setExpiry(data.qr_expires_at);updateState(data)}
async function refreshStatus(){if(!panel.dataset.statusUrl)return;try{updateState(await requestJson(panel.dataset.statusUrl))}catch(error){document.getElementById('syncStatus').textContent='Koneksi terputus, mencoba lagi...';showError(error)}}
function startPolling(){clearInterval(pollingTimer);pollingTimer=setInterval(refreshStatus,3000)}
document.querySelectorAll('.open-session').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;try{const data=await requestJson(button.dataset.url,'POST');panel.dataset.sessionId=data.id;const statusPath=new URL(button.dataset.url,window.location.href).pathname.replace(/\/sesi\/[^/]+\/buka$/,'/sesi/'+data.id+'/status');panel.dataset.statusUrl=window.location.origin+statusPath;document.getElementById('sessionTitle').textContent=`${data.jadwal.mapel} • ${data.jadwal.kelas}`;showQr(data);showSuccess('Sesi berhasil dibuka. QR aktif selama 5 menit.');await refreshStatus();startPolling()}catch(error){showError(error);button.disabled=false}}));
document.getElementById('refreshQr').addEventListener('click',async()=>{if(!panel.dataset.sessionId)return;const button=document.getElementById('refreshQr');button.disabled=true;try{const data=await requestJson(panel.dataset.qrTemplate.replace('__ID__',panel.dataset.sessionId),'POST');showQr(data);showSuccess('QR Code diperbarui dan aktif 5 menit lagi.')}catch(error){showError(error)}finally{button.disabled=document.getElementById('sessionStatus').textContent!=='Berlangsung'}});
document.getElementById('closeSession').addEventListener('click',()=>closeConfirm.showModal());document.getElementById('cancelClose').addEventListener('click',()=>closeConfirm.close());closeConfirm.addEventListener('click',event=>{if(event.target===closeConfirm)closeConfirm.close()});
document.getElementById('confirmClose').addEventListener('click',async()=>{const button=document.getElementById('confirmClose');button.disabled=true;try{const data=await requestJson(panel.dataset.closeTemplate.replace('__ID__',panel.dataset.sessionId),'POST');document.getElementById('qrImage').replaceChildren();updateState(data);closeConfirm.close();showSuccess('Sesi ditutup. Siswa yang belum absen telah tercatat Alfa.');clearInterval(pollingTimer)}catch(error){showError(error)}finally{button.disabled=false}});
if(panel.dataset.statusUrl){refreshStatus();startPolling()}setExpiry(panel.dataset.qrExpiresAt);expiryTimer=setInterval(updateCountdown,1000);
</script>
</body></html>
