<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="icon" href="{{ asset('logo.jpg') }}" type="image/jpeg"><title>Presensi Guru - SMP Muhammadiyah 44</title><link rel="stylesheet" href="{{ asset('guru css/presensiguru.css') }}?v=3"></head>
<body>
<div class="page-loader" id="pageLoader"><div class="loader-logo-wrap"><div class="loader-spinner"></div><div class="loader-logo"><img src="{{ asset('logo.jpg') }}" alt="Logo sekolah"></div></div><div class="loader-text">SMP Muhammadiyah 44</div><div class="loader-subtext">Memuat presensi guru...</div></div>
<div class="guru-page" id="guruPage"><aside class="sidebar" id="sidebar"><div class="sidebar-header"><div class="sidebar-brand"><div class="sidebar-logo"><img src="{{ asset('logo.jpg') }}" alt="Logo sekolah"></div><div><div class="sidebar-title">SMP Muhammadiyah 44</div><div class="sidebar-subtitle">Portal Guru</div></div></div><button class="sidebar-close-btn" onclick="toggleSidebar()">✕</button></div><div class="sidebar-section-label">Menu</div><nav class="sidebar-nav"><a class="nav-item" style="--delay:1" href="{{ route('guru.dashboard') }}"><span class="nav-icon-box">🏠</span>Dashboard</a><a class="nav-item active" style="--delay:2" href="{{ route('guru.presensi-guru') }}"><span class="nav-icon-box">🧾</span>Presensi Guru</a><a class="nav-item" style="--delay:3" href="{{ route('guru.jadwal') }}"><span class="nav-icon-box">📅</span>Jadwal Mengajar</a><a class="nav-item" style="--delay:4" href="{{ route('guru.presensi-murid') }}"><span class="nav-icon-box">👥</span>Presensi Murid</a><a class="nav-item" style="--delay:5" href="{{ route('guru.riwayat-presensi') }}"><span class="nav-icon-box">🕘</span>Riwayat Presensi</a><a class="nav-item" style="--delay:6" href="{{ route('guru.profil') }}"><span class="nav-icon-box">👤</span>Profil</a></nav><div class="sidebar-footer"><div class="sidebar-footer-user"><div class="avatar">AF</div><div><div class="name">Ust. Ahmad Fauzi</div><div class="role">Guru Mata Pelajaran</div></div></div><form action="{{ route('guru.logout') }}" method="POST">@csrf<button class="nav-item logout-item" type="submit"><span class="nav-icon-box">🚪</span>Keluar</button></form></div></aside><div class="sidebar-overlay" id="sidebarOverlay" onclick="toggleSidebar()"></div>
<header class="topbar"><div class="topbar-left"><button class="burger-btn" id="burgerBtn" onclick="toggleSidebar()"><span></span><span></span><span></span></button><div class="brand-wrap"><span class="brand-dot"></span><span class="portal-tag">Portal Guru • SMP Muhammadiyah 44</span></div></div><div class="topbar-right"><div class="date-pill" id="liveDatetime">Memuat waktu...</div><div class="bell-btn">🔔<span class="badge"></span></div><div class="profile-pill"><div class="avatar">AF</div><div class="profile-meta"><div class="name">Ust. Ahmad Fauzi, S.Pd.</div><div class="role">Guru IPA &amp; Matematika</div></div></div></div></header>
<main class="content">
	<div class="page-header"><div><h1>Presensi Guru</h1><p>Kehadiran sekolah untuk {{ now()->locale('id')->translatedFormat('l, j F Y') }}.</p></div></div>
	@if(session('success'))<div class="panel" role="status">{{ session('success') }}</div>@endif
	@if($errors->any())<div class="panel" role="alert">{{ $errors->first() }}</div>@endif
	<section class="panel"><div class="panel-head"><div class="panel-title">Kehadiran Sekolah</div></div>
		<div class="cards-two" style="padding:20px">
			<div class="attendance-card"><div class="card-top"><div><span class="muted">ABSEN DATANG</span><h3>Absen Masuk Sekolah</h3><small>{{ $presensi?->jam_masuk ? 'Tercatat hari ini' : 'Belum ada catatan masuk' }}</small></div><span class="status-pill {{ $presensi?->jam_masuk ? 'hadir' : 'izin' }}">{{ $presensi?->jam_masuk ? 'Sudah Absen' : 'Belum Absen' }}</span></div>
				<div class="big-time">{{ $presensi?->jam_masuk ? substr($presensi->jam_masuk, 0, 5) : '--:--' }} <small>WIB</small></div>
				@if($presensi?->foto_masuk)<p><a href="{{ asset('storage/'.$presensi->foto_masuk) }}" target="_blank" rel="noopener">Lihat foto masuk</a></p>@endif
				@if(! $presensi?->jam_masuk)<form class="card-foot" action="{{ route('guru.presensi.masuk') }}" method="POST" enctype="multipart/form-data">@csrf<label>Foto selfie/bukti<input type="file" name="foto" accept="image/jpeg,image/png,image/webp" capture="environment" required></label><button class="btn btn-primary" type="submit">Absen Masuk</button></form>@endif
			</div>
			<div class="attendance-card"><div class="card-top"><div><span class="muted">ABSEN KEPULANGAN</span><h3>Absen Pulang Sekolah</h3><small>{{ $presensi?->jam_pulang ? 'Tercatat hari ini' : 'Absen masuk harus tercatat lebih dahulu.' }}</small></div><span class="status-pill {{ $presensi?->jam_pulang ? 'hadir' : 'izin' }}">{{ $presensi?->jam_pulang ? 'Sudah Absen' : 'Belum Absen' }}</span></div>
				<div class="big-time">{{ $presensi?->jam_pulang ? substr($presensi->jam_pulang, 0, 5) : '--:--' }} <small>WIB</small></div>
				@if($presensi?->foto_pulang)<p><a href="{{ asset('storage/'.$presensi->foto_pulang) }}" target="_blank" rel="noopener">Lihat foto pulang</a></p>@endif
				@if(! $presensi?->jam_pulang && $presensi?->jam_masuk)<form class="card-foot" action="{{ route('guru.presensi.pulang') }}" method="POST" enctype="multipart/form-data">@csrf<label>Foto selfie/bukti<input type="file" name="foto" accept="image/jpeg,image/png,image/webp" capture="environment" required></label><button class="btn btn-primary" type="submit">Absen Pulang</button></form>@endif
			</div>
		</div>
	</section>
	<section class="panel" style="margin-top:20px"><div class="panel-head"><div class="panel-title">Jadwal Mengajar Hari Ini</div><span class="muted">{{ $jadwals->count() }} jadwal</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Jam KBM</th><th>Mata Pelajaran</th><th>Kelas</th><th>Status Sesi</th><th>Aksi</th></tr></thead><tbody>
		@forelse($jadwals as $jadwal)@php($jadwalSesi = $jadwal->sesiPelajarans->first())<tr><td>{{ substr($jadwal->jam_mulai, 0, 5) }}-{{ substr($jadwal->jam_selesai, 0, 5) }}</td><td>{{ $jadwal->mapel->nama_mapel }}</td><td>{{ $jadwal->kelas->nama_kelas }}</td><td>{{ $jadwalSesi?->status_sesi ?? 'Belum' }}</td><td><a class="btn {{ $jadwalSesi?->status_sesi === 'Berlangsung' ? 'btn-primary' : '' }}" href="{{ route('guru.presensi-murid') }}">Kelola Presensi</a></td></tr>@empty<tr><td colspan="5">Tidak ada jadwal mengajar untuk hari ini.</td></tr>@endforelse
	</tbody></table></div></section>
	<footer class="footer"><span>Sistem Presensi &amp; Manajemen Akademik SMP Muhammadiyah 44 Tangerang Selatan</span><span>© {{ date('Y') }} SMP Muhammadiyah 44 Tangerang Selatan</span></footer>
</main></div>
<script>window.addEventListener('load',()=>setTimeout(()=>{pageLoader.classList.add('hide');guruPage.classList.add('loaded')},500));function toggleSidebar(){sidebar.classList.toggle('open');sidebarOverlay.classList.toggle('show');burgerBtn.classList.toggle('active')}function updateLiveDatetime(){let n=new Date(),d=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'],m=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],p=x=>String(x).padStart(2,'0');liveDatetime.innerHTML=`<span class="date-html">${d[n.getDay()]}, ${n.getDate()} ${m[n.getMonth()]} ${n.getFullYear()}</span><span class="sep"> | </span><span class="time-html">${p(n.getHours())}:${p(n.getMinutes())}:${p(n.getSeconds())} WIB</span>`}updateLiveDatetime();setInterval(updateLiveDatetime,1000)</script>
</body></html>
