<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="icon" href="{{ asset('logo.jpg') }}" type="image/jpeg">
  <title>Presensi Murid - SMP Muhammadiyah 44</title>
  <link rel="stylesheet" href="{{ asset('guru css/presensimurid.css') }}?v=3">
  <link rel="stylesheet" href="{{ asset('guru css/portal-responsive.css') }}?v=1">
</head>
<body>
@php
  $guruInitials = collect(preg_split('/\s+/', trim($guru->nama_lengkap)))
    ->filter()
    ->take(2)
    ->map(fn ($bagian) => mb_substr($bagian, 0, 1))
    ->implode('');
@endphp
<div class="page-loader" id="pageLoader"><div class="loader-logo-wrap"><div class="loader-spinner"></div><div class="loader-logo"><img src="{{ asset('logo.jpg') }}" alt="Logo sekolah"></div></div><div class="loader-text">SMP Muhammadiyah 44</div><div class="loader-subtext">Memuat presensi murid...</div></div>
<div class="guru-page" id="guruPage">
  <aside class="sidebar" id="sidebar"><div class="sidebar-header"><div class="sidebar-brand"><div class="sidebar-logo"><img src="{{ asset('logo.jpg') }}" alt="Logo sekolah"></div><div><div class="sidebar-title">SMP Muhammadiyah 44</div><div class="sidebar-subtitle">Portal Guru</div></div></div><button class="sidebar-close-btn" onclick="toggleSidebar()">✕</button></div><div class="sidebar-section-label">Menu</div><nav class="sidebar-nav">
    <a class="nav-item" style="--delay:1" href="{{ route('guru.dashboard') }}"><span class="nav-icon-box">🏠</span>Dashboard</a><a class="nav-item" style="--delay:2" href="{{ route('guru.presensi-guru') }}"><span class="nav-icon-box">🧾</span>Presensi Guru</a><a class="nav-item" style="--delay:3" href="{{ route('guru.jadwal') }}"><span class="nav-icon-box">📅</span>Jadwal Mengajar</a><a class="nav-item active" style="--delay:4" href="{{ route('guru.presensi-murid') }}"><span class="nav-icon-box">👥</span>Presensi Murid</a><a class="nav-item" style="--delay:5" href="{{ route('guru.riwayat-presensi') }}"><span class="nav-icon-box">🕘</span>Riwayat Presensi</a><a class="nav-item" style="--delay:6" href="{{ route('guru.profil') }}"><span class="nav-icon-box">👤</span>Profil</a>
  </nav><div class="sidebar-footer"><div class="sidebar-footer-user"><div class="avatar">{{ mb_strtoupper($guruInitials) }}</div><div><div class="name">{{ $guru->nama_lengkap }}</div><div class="role">{{ $mapelGuru ?: 'Guru Mata Pelajaran' }}</div></div></div><form action="{{ route('guru.logout') }}" method="POST">@csrf<button class="nav-item logout-item" type="submit"><span class="nav-icon-box">🚪</span>Keluar</button></form></div></aside><div class="sidebar-overlay" id="sidebarOverlay" onclick="toggleSidebar()"></div>
  <header class="topbar"><div class="topbar-left"><button class="burger-btn" id="burgerBtn" onclick="toggleSidebar()"><span></span><span></span><span></span></button><div class="brand-wrap"><span class="brand-dot"></span><span class="portal-tag">Portal Guru • SMP Muhammadiyah 44</span></div></div><div class="topbar-right"><div class="date-pill" id="liveDatetime">Memuat waktu...</div><div class="bell-btn" aria-hidden="true">🔔<span class="badge"></span></div><div class="profile-pill"><div class="avatar">{{ mb_strtoupper($guruInitials) }}</div><div class="profile-meta"><div class="name">{{ $guru->nama_lengkap }}</div><div class="role">{{ $mapelGuru ?: 'Guru Mata Pelajaran' }}</div></div></div></div></header>
  <main class="content">
    <div class="page-header"><div><h1>Presensi Murid</h1><p>Kelola sesi mengajar dan kehadiran kelas hari ini.</p></div><span class="term-chip">{{ now()->locale('id')->translatedFormat('l, j F Y') }}</span></div>
    @if(session('success'))<div class="panel" role="status">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="panel" role="alert">{{ $errors->first() }}</div>@endif
    <section class="panel schedule-panel">
      <div class="panel-head schedule-panel-head"><div class="panel-title">Jadwal Mengajar Hari Ini</div><span class="schedule-count">{{ $jadwals->count() }} jadwal dari database</span></div>
      <div class="schedule-list" role="list" aria-label="Jadwal mengajar hari ini">
        <div class="schedule-list-head" aria-hidden="true"><span>Jam</span><span>Mata Pelajaran</span><span>Kelas</span><span>Status Sesi</span><span>Aksi</span></div>
        @forelse($jadwals as $jadwal)
          @php($jadwalSesi = $jadwal->sesiPelajarans->first())
          <article class="schedule-item" data-jadwal-id="{{ $jadwal->id }}" role="listitem">
            <div class="schedule-cell schedule-time" data-label="Jam"><strong>{{ substr($jadwal->jam_mulai, 0, 5) }}-{{ substr($jadwal->jam_selesai, 0, 5) }}</strong></div>
            <div class="schedule-cell schedule-subject" data-field="mapel" data-label="Mata Pelajaran"><strong>{{ $jadwal->mapel->nama_mapel }}</strong></div>
            <div class="schedule-cell schedule-class" data-field="kelas" data-label="Kelas"><span class="schedule-class-chip">{{ $jadwal->kelas->nama_kelas }}</span></div>
            <div class="schedule-cell schedule-state" data-label="Status Sesi"><span class="schedule-status {{ $jadwalSesi?->status_sesi === 'Berlangsung' ? 'is-live' : ($jadwalSesi?->status_sesi === 'Selesai' ? 'is-done' : 'is-idle') }}" data-session-state>{{ $jadwalSesi?->status_sesi ?? 'Belum' }}</span></div>
            <div class="schedule-cell schedule-action" data-session-action>
              @if($jadwalSesi?->status_sesi === 'Berlangsung')<a class="btn btn-primary" href="{{ route('guru.presensi-murid', ['sesi' => $jadwalSesi->id]) }}">Kelola Sesi</a>
              @elseif($jadwalSesi?->status_sesi !== 'Selesai')<button class="btn btn-primary open-session" type="button" data-jadwal-id="{{ $jadwal->id }}" data-mapel="{{ $jadwal->mapel->nama_mapel }}" data-kelas="{{ $jadwal->kelas->nama_kelas }}" data-url="{{ route('guru.sesi.open', ['jadwal' => $jadwal->id]) }}">Mulai Presensi</button>
              @else<span class="muted">Selesai</span>@endif
            </div>
          </article>
        @empty
          <div class="schedule-empty" role="status">Tidak ada jadwal mengajar untuk hari ini.</div>
        @endforelse
      </div>
    </section>
    <section class="qr-layout" id="sessionPanel" data-session-id="{{ $sesi?->id }}" data-status-url="{{ $sesi ? route('guru.sesi.status', ['sesi' => $sesi->id]) : '' }}" data-qr-template="{{ route('guru.sesi.qr', ['sesi' => '__ID__']) }}" data-close-template="{{ route('guru.sesi.close', ['sesi' => '__ID__']) }}" data-delete-template="{{ route('guru.sesi.destroy', ['sesi' => '__ID__']) }}" data-open-template="{{ route('guru.sesi.open', ['jadwal' => '__ID__']) }}" data-manage-template="{{ route('guru.presensi-murid', ['sesi' => '__ID__']) }}" data-manual-template="{{ route('guru.presensi-murid.update', ['presensi' => '__ID__']) }}" data-qr-expires-at="{{ $sesi?->qr_expires_at?->toIso8601String() }}">
      <div class="panel qr-panel"><div class="panel-head"><div class="panel-title">QR Code Sesi</div><span class="status-pill {{ $sesi?->status_sesi === 'Berlangsung' ? 'is-live' : ($sesi?->status_sesi === 'Selesai' ? 'is-done' : 'is-idle') }}" id="sessionStatus">{{ $sesi?->status_sesi ?? 'Belum ada sesi' }}</span></div>
        <div class="qr-box" id="qrBox"><div class="qr-visual {{ $sesi?->qr_expires_at?->isPast() ? 'is-expired' : '' }}" id="qrVisual">
          <div class="qr-image" id="qrImage">@if($sesi?->status_sesi === 'Berlangsung' && $sesi->qr_token && $sesi->qr_expires_at?->isFuture()){!! \SimpleSoftwareIO\QrCode\Facades\QrCode::format('svg')->size(360)->margin(2)->generate($sesi->qr_token) !!}@endif</div>
          <div class="qr-expired-overlay" id="qrExpiredOverlay" {{ $sesi?->qr_expires_at?->isPast() || ! $sesi ? '' : 'hidden' }}>QR Kadaluarsa</div>
        </div>
          <strong id="sessionTitle">{{ $sesi ? $sesi->jadwal->mapel->nama_mapel.' • '.$sesi->jadwal->kelas->nama_kelas : 'Pilih jadwal untuk memulai sesi' }}</strong>
          <span class="qr-countdown" id="qrCountdown" role="timer" aria-live="polite">QR belum aktif</span>
          <small id="qrExpiry">{{ $sesi?->qr_expires_at?->format('H:i:s') ?? 'QR akan berlaku 5 menit' }}</small>
        </div>
        <div class="qr-actions"><div class="attendance-tally" id="attendanceCounts" aria-live="polite">Belum ada sesi aktif</div><div class="session-buttons"><button class="btn btn-primary refresh-qr" id="refreshQr" type="button" {{ $sesi?->status_sesi === 'Berlangsung' ? '' : 'disabled' }}>🔄 Perbarui QR</button><button class="btn btn-close-session" id="closeSession" type="button" {{ $sesi?->status_sesi === 'Berlangsung' ? '' : 'disabled' }}>Tutup Sesi</button><button class="btn btn-cancel-session" id="cancelSession" type="button" {{ $sesi?->status_sesi === 'Berlangsung' ? '' : 'disabled' }}>Batalkan Presensi</button></div></div>
      </div>
      <div class="panel"><div class="panel-head"><div class="panel-title">Daftar Presensi Murid</div><span class="muted" id="syncStatus">Menunggu sesi dimulai</span></div><div class="student-grid" id="studentList"><p class="empty-attendance">Buka sesi untuk menampilkan daftar murid.</p></div></div>
    </section>
    <div class="feedback-message" id="feedback" role="status" aria-live="polite" aria-atomic="true"></div>
    <footer class="footer"><span>Sistem Presensi &amp; Manajemen Akademik SMP Muhammadiyah 44 Tangerang Selatan</span><span>© {{ date('Y') }} SMP Muhammadiyah 44 Tangerang Selatan</span></footer>
  </main>
</div>
<dialog class="session-confirm" id="closeConfirm" aria-labelledby="closeConfirmTitle"><div class="confirm-content"><span class="confirm-icon">!</span><h2 id="closeConfirmTitle">Tutup sesi presensi?</h2><p>Apakah Anda yakin ingin menutup sesi? Siswa yang belum absen akan otomatis tercatat <strong>ALFA</strong>.</p><div class="confirm-actions"><button class="btn" id="cancelClose" type="button">Kembali</button><button class="btn btn-close-session" id="confirmClose" type="button">Ya, Tutup Sesi &amp; Simpan</button></div></div></dialog>
<dialog class="session-confirm" id="startConfirm" aria-labelledby="startConfirmTitle"><div class="confirm-content"><span class="confirm-icon start-icon">?</span><h2 id="startConfirmTitle">Mulai presensi?</h2><p id="startConfirmMessage">Apakah Anda yakin ingin membuka sesi presensi ini?</p><div class="confirm-actions"><button class="btn" id="cancelStart" type="button">Kembali</button><button class="btn btn-primary" id="confirmStart" type="button">Ya, Mulai</button></div></div></dialog>
<dialog class="session-confirm" id="cancelConfirm" aria-labelledby="cancelConfirmTitle"><div class="confirm-content"><span class="confirm-icon">!</span><h2 id="cancelConfirmTitle">Batalkan presensi?</h2><p>Sesi dan seluruh data presensi murid di dalamnya akan <strong>dihapus permanen</strong>. Tindakan ini tidak dapat dibatalkan.</p><div class="confirm-actions"><button class="btn" id="dismissCancel" type="button">Kembali</button><button class="btn btn-cancel-session" id="confirmCancel" type="button">Ya, Hapus Sesi</button></div></div></dialog>
<script>
window.addEventListener('load',()=>setTimeout(()=>{pageLoader.classList.add('hide');guruPage.classList.add('loaded')},500));
function toggleSidebar(){sidebar.classList.toggle('open');sidebarOverlay.classList.toggle('show');burgerBtn.classList.toggle('active')}
function updateLiveDatetime(){const n=new Date(),d=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'],m=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],p=x=>String(x).padStart(2,'0');liveDatetime.textContent=`${d[n.getDay()]}, ${n.getDate()} ${m[n.getMonth()]} ${n.getFullYear()} | ${p(n.getHours())}:${p(n.getMinutes())}:${p(n.getSeconds())} WIB`}
updateLiveDatetime();setInterval(updateLiveDatetime,1000);
const panel=document.getElementById('sessionPanel'),feedback=document.getElementById('feedback'),csrf=document.querySelector('meta[name="csrf-token"]')?.content,closeConfirm=document.getElementById('closeConfirm'),startConfirm=document.getElementById('startConfirm'),cancelConfirm=document.getElementById('cancelConfirm');
let lastRowsFingerprint='',pollingTimer=null,expiryTimer=null,feedbackTimer=null,pendingOpenButton=null;
async function requestJson(url,method='GET',body=null){const response=await fetch(url,{method,headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.message||Object.values(data.errors||{}).flat()[0]||'Permintaan gagal.');return data}
function showFeedback(type,message){clearTimeout(feedbackTimer);feedback.className=`feedback-message is-${type} is-visible`;feedback.textContent=message;feedbackTimer=setTimeout(()=>feedback.classList.remove('is-visible'),type==='error'?6500:4200)}
function showError(error){showFeedback('error',error.message)}
function showSuccess(message){showFeedback('success',message)}
function updateScheduleRow(data){const jadwalId=data.jadwal_id||data.jadwal?.id;if(!jadwalId)return;const row=document.querySelector(`.schedule-item[data-jadwal-id="${jadwalId}"]`);if(!row)return;const state=row.querySelector('[data-session-state]'),action=row.querySelector('[data-session-action]'),status=data.status_sesi==='Dibatalkan'?'Belum':data.status_sesi;state.textContent=status;state.classList.remove('is-live','is-done','is-idle');state.classList.add(status==='Berlangsung'?'is-live':status==='Selesai'?'is-done':'is-idle');action.replaceChildren();if(status==='Berlangsung'){const link=document.createElement('a');link.className='btn btn-primary';link.href=panel.dataset.manageTemplate.replace('__ID__',data.id);link.textContent='Kelola Sesi';action.append(link)}else if(status==='Selesai'){const label=document.createElement('span');label.className='muted';label.textContent='Selesai';action.append(label)}else{const button=document.createElement('button');button.type='button';button.className='btn btn-primary open-session';button.dataset.jadwalId=jadwalId;button.dataset.mapel=row.querySelector('[data-field="mapel"]').textContent.trim();button.dataset.kelas=row.querySelector('[data-field="kelas"]').textContent.trim();button.dataset.url=panel.dataset.openTemplate.replace('__ID__',jadwalId);button.textContent='Mulai Presensi';action.append(button)}}
function renderStudents(rows){const fingerprint=JSON.stringify(rows);if(fingerprint===lastRowsFingerprint)return;lastRowsFingerprint=fingerprint;const list=document.getElementById('studentList');list.replaceChildren();if(!rows.length){const empty=document.createElement('p');empty.className='empty-attendance';empty.textContent=panel.dataset.sessionId?'Belum ada murid aktif di kelas ini.':'Buka sesi untuk menampilkan daftar murid.';list.append(empty);document.getElementById('attendanceCounts').textContent=panel.dataset.sessionId?'Belum ada data presensi murid':'Belum ada sesi aktif';return}const counts={Hadir:0,Izin:0,Sakit:0,Alfa:0,'Belum Absen':0};const statusClasses={Hadir:'hadir',Izin:'izin',Sakit:'sakit',Alfa:'alfa','Belum Absen':'belum-absen'};rows.forEach(row=>{counts[row.status]=(counts[row.status]||0)+1;const line=document.createElement('div');line.className=`student-row is-${statusClasses[row.status]||'belum-absen'}`;line.innerHTML='<div class="student-identity"><div><span class="student-name"></span><span class="student-id"></span></div><span class="attendance-status"></span></div><div class="radio-group"></div>';line.querySelector('.student-name').textContent=row.nama;line.querySelector('.student-id').textContent=row.nisn;line.querySelector('.attendance-status').textContent=row.status;line.setAttribute('aria-label',`${row.nama}, ${row.status}`);const radios=line.querySelector('.radio-group');['Hadir','Izin','Sakit','Alfa'].forEach(status=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name=`status-${row.id}`;input.value=status;input.checked=row.status===status;input.disabled=document.getElementById('sessionStatus').textContent!=='Berlangsung';input.addEventListener('change',async()=>{try{await requestJson(panel.dataset.manualTemplate.replace('__ID__',row.id),'PUT',{status});lastRowsFingerprint='';await refreshStatus();showSuccess('Status presensi tersimpan.')}catch(error){showError(error)}});label.append(input,document.createTextNode(` ${status}`));radios.append(label)});list.append(line)});document.getElementById('attendanceCounts').textContent=`Hadir ${counts.Hadir||0} dari ${rows.length} murid • Izin ${counts.Izin||0} • Sakit ${counts.Sakit||0} • Alfa ${counts.Alfa||0} • Belum ${counts['Belum Absen']||0}`}
function setExpiry(value){panel.dataset.qrExpiresAt=value||'';document.getElementById('qrExpiry').textContent=value?`Berlaku sampai ${new Date(value).toLocaleTimeString('id-ID')}`:'QR tidak aktif';updateCountdown()}
function updateCountdown(){const expiry=Date.parse(panel.dataset.qrExpiresAt||''),active=document.getElementById('sessionStatus').textContent==='Berlangsung',seconds=Math.ceil((expiry-Date.now())/1000),hasExpiry=Number.isFinite(expiry),expired=active&&(!hasExpiry||seconds<=0),visual=document.getElementById('qrVisual'),overlay=document.getElementById('qrExpiredOverlay'),refresh=document.getElementById('refreshQr'),countdown=document.getElementById('qrCountdown');visual.classList.toggle('is-expired',expired);countdown.classList.toggle('is-expired',expired);overlay.hidden=!expired;if(expired){countdown.textContent='QR Kadaluarsa';refresh.classList.add('needs-refresh')}else if(active){countdown.textContent=`QR Aktif: ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;refresh.classList.remove('needs-refresh')}else{countdown.textContent=panel.dataset.sessionId?'QR tidak aktif':'QR belum aktif';refresh.classList.remove('needs-refresh')}}
function updateState(data){const status=document.getElementById('sessionStatus');status.textContent=data.status_sesi;status.classList.remove('is-live','is-done','is-idle');status.classList.add(data.status_sesi==='Berlangsung'?'is-live':data.status_sesi==='Selesai'?'is-done':'is-idle');document.getElementById('refreshQr').disabled=data.status_sesi!=='Berlangsung';document.getElementById('closeSession').disabled=data.status_sesi!=='Berlangsung';document.getElementById('syncStatus').textContent=data.status_sesi==='Berlangsung'?'Pembaruan otomatis setiap 3 detik':data.status_sesi;if(data.jadwal)document.getElementById('sessionTitle').textContent=`${data.jadwal.mapel} • ${data.jadwal.kelas}`;if(data.jadwal_id||data.jadwal?.id)updateScheduleRow(data);if(data.qr_expires_at!==undefined)setExpiry(data.qr_expires_at);renderStudents(data.presensi||[]);updateCountdown()}
function showQr(data){document.getElementById('qrImage').innerHTML=data.qr_svg;setExpiry(data.qr_expires_at);updateState(data)}
async function refreshStatus(){if(!panel.dataset.statusUrl)return;try{updateState(await requestJson(panel.dataset.statusUrl))}catch(error){document.getElementById('syncStatus').textContent='Koneksi terputus, mencoba lagi...';showError(error)}}
function startPolling(){clearInterval(pollingTimer);pollingTimer=setInterval(refreshStatus,3000)}
function resetCancelledSession(data){clearInterval(pollingTimer);panel.dataset.sessionId='';panel.dataset.statusUrl='';panel.dataset.qrExpiresAt='';updateScheduleRow(data);document.getElementById('qrImage').replaceChildren();document.getElementById('qrVisual').classList.remove('is-expired');document.getElementById('qrExpiredOverlay').hidden=true;document.getElementById('sessionTitle').textContent='Pilih jadwal untuk memulai sesi';document.getElementById('qrExpiry').textContent='QR akan berlaku 5 menit';document.getElementById('sessionStatus').textContent='Belum ada sesi';document.getElementById('sessionStatus').className='status-pill is-idle';document.getElementById('refreshQr').disabled=true;document.getElementById('closeSession').disabled=true;document.getElementById('cancelSession').disabled=true;document.getElementById('syncStatus').textContent='Menunggu sesi dimulai';lastRowsFingerprint='';renderStudents([]);updateCountdown()}
function beginOpenSession(button){pendingOpenButton=button;document.getElementById('startConfirmMessage').textContent=`Apakah Anda yakin ingin membuka sesi presensi untuk ${button.dataset.mapel} - ${button.dataset.kelas}?`;startConfirm.showModal()}
document.addEventListener('click',event=>{const button=event.target.closest('.open-session');if(button&&!button.disabled)beginOpenSession(button)});
document.getElementById('cancelStart').addEventListener('click',()=>{pendingOpenButton=null;startConfirm.close()});
document.getElementById('confirmStart').addEventListener('click',async()=>{if(!pendingOpenButton)return;const button=pendingOpenButton,confirmButton=document.getElementById('confirmStart');confirmButton.disabled=true;button.disabled=true;try{const data=await requestJson(button.dataset.url,'POST',{jadwal_pelajaran_id:button.dataset.jadwalId});panel.dataset.sessionId=data.id;const statusPath=new URL(button.dataset.url,window.location.href).pathname.replace(/\/sesi\/[^/]+\/buka$/,'/sesi/'+data.id+'/status');panel.dataset.statusUrl=window.location.origin+statusPath;document.getElementById('sessionTitle').textContent=`${data.jadwal.mapel} • ${data.jadwal.kelas}`;showQr(data);showSuccess('Sesi berhasil dibuka. QR aktif selama 5 menit.');startPolling();startConfirm.close()}catch(error){startConfirm.close();showError(error);button.disabled=false}finally{pendingOpenButton=null;confirmButton.disabled=false}});
document.getElementById('refreshQr').addEventListener('click',async()=>{if(!panel.dataset.sessionId)return;const button=document.getElementById('refreshQr');button.disabled=true;try{const data=await requestJson(panel.dataset.qrTemplate.replace('__ID__',panel.dataset.sessionId),'POST');showQr(data);showSuccess('QR Code diperbarui dan aktif 5 menit lagi.')}catch(error){showError(error)}finally{button.disabled=document.getElementById('sessionStatus').textContent!=='Berlangsung'}});
document.getElementById('closeSession').addEventListener('click',()=>closeConfirm.showModal());document.getElementById('cancelClose').addEventListener('click',()=>closeConfirm.close());closeConfirm.addEventListener('click',event=>{if(event.target===closeConfirm)closeConfirm.close()});
document.getElementById('confirmClose').addEventListener('click',async()=>{const button=document.getElementById('confirmClose');button.disabled=true;try{const data=await requestJson(panel.dataset.closeTemplate.replace('__ID__',panel.dataset.sessionId),'POST');document.getElementById('qrImage').replaceChildren();updateState(data);closeConfirm.close();showSuccess('Sesi ditutup. Siswa yang belum absen telah tercatat Alfa.');clearInterval(pollingTimer)}catch(error){closeConfirm.close();showError(error)}finally{button.disabled=false}});
document.getElementById('cancelSession').addEventListener('click',()=>cancelConfirm.showModal());
document.getElementById('dismissCancel').addEventListener('click',()=>cancelConfirm.close());
document.getElementById('confirmCancel').addEventListener('click',async()=>{const button=document.getElementById('confirmCancel');button.disabled=true;try{const data=await requestJson(panel.dataset.deleteTemplate.replace('__ID__',panel.dataset.sessionId),'DELETE');resetCancelledSession(data);cancelConfirm.close();showSuccess('Presensi dibatalkan. Sesi dan seluruh data murid telah dihapus permanen.')}catch(error){cancelConfirm.close();showError(error)}finally{button.disabled=false}});
if(panel.dataset.statusUrl){refreshStatus();startPolling()}setExpiry(panel.dataset.qrExpiresAt);expiryTimer=setInterval(updateCountdown,1000);
</script>
</body></html>
