<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Profil Guru - SMP Muhammadiyah 44</title><link rel="stylesheet" href="{{ asset('guru css/profil.css') }}?v=1"></head>
<body>
<div class="guru-page" id="guruPage"><aside class="sidebar" id="sidebar"><div class="sidebar-header"><div class="sidebar-brand"><div class="sidebar-logo"><img src="{{ asset('logo.jpg') }}" alt="Logo sekolah"></div><div><div class="sidebar-title">SMP Muhammadiyah 44</div><div class="sidebar-subtitle">Portal Guru</div></div></div><button class="sidebar-close-btn" onclick="toggleSidebar()">✕</button></div><div class="sidebar-section-label">Menu</div><nav class="sidebar-nav"><a class="nav-item" style="--delay:1" href="{{ route('guru.dashboard') }}"><span class="nav-icon-box">🏠</span>Dashboard</a><a class="nav-item" style="--delay:2" href="{{ route('guru.presensi-guru') }}"><span class="nav-icon-box">🧾</span>Presensi Guru</a><a class="nav-item" style="--delay:3" href="{{ route('guru.jadwal') }}"><span class="nav-icon-box">📅</span>Jadwal Mengajar</a><a class="nav-item" style="--delay:4" href="{{ route('guru.presensi-murid') }}"><span class="nav-icon-box">👥</span>Presensi Murid</a><a class="nav-item" style="--delay:5" href="{{ route('guru.riwayat-presensi') }}"><span class="nav-icon-box">🕘</span>Riwayat Presensi</a><a class="nav-item active" style="--delay:6" href="{{ route('guru.profil') }}"><span class="nav-icon-box">👤</span>Profil</a></nav><div class="sidebar-footer"><div class="sidebar-footer-user"><div class="avatar">AF</div><div><div class="name">Ust. Ahmad Fauzi</div><div class="role">Guru Mata Pelajaran</div></div></div><form action="{{ route('guru.logout') }}" method="POST">@csrf<button class="nav-item logout-item" type="submit"><span class="nav-icon-box">🚪</span>Keluar</button></form></div></aside><div class="sidebar-overlay" id="sidebarOverlay" onclick="toggleSidebar()"></div>
<header class="topbar"><div class="topbar-left"><button class="burger-btn" id="burgerBtn" onclick="toggleSidebar()"><span></span><span></span><span></span></button><div class="brand-wrap"><span class="brand-dot"></span><span class="portal-tag">Portal Guru • SMP Muhammadiyah 44</span></div></div><div class="topbar-right"><div class="date-pill" id="liveDatetime">Memuat waktu...</div><div class="bell-btn">🔔<span class="badge"></span></div><div class="profile-pill"><div class="avatar">AF</div><div class="profile-meta"><div class="name">Ust. Ahmad Fauzi, S.Pd.</div><div class="role">Guru IPA &amp; Matematika</div></div></div></div></header>
<main class="content"><div class="page-header"><div><h1>Profil Guru</h1><p>Kelola informasi akun dan data kepegawaian Anda.</p></div></div><section class="profile-layout"><div class="panel profile-card"><div class="avatar">AF</div><h2>Ust. Ahmad Fauzi, S.Pd.</h2><p>Guru IPA &amp; Matematika</p><span class="status-pill hadir">● Akun Aktif</span></div><div class="panel profile-form"><div class="panel-head" style="padding:0 0 16px"><div class="panel-title">Informasi Profil</div></div><div class="form-grid"><div class="form-field"><label>Nama Lengkap</label><input value="Ahmad Fauzi" readonly></div><div class="form-field"><label>Username</label><input value="ahmad.fauzi" readonly></div><div class="form-field"><label>Email</label><input value="ahmad.fauzi@smpmuh44.sch.id" readonly></div><div class="form-field"><label>Nomor Telepon</label><input value="0812-0000-4444" readonly></div><div class="form-field full"><label>Mata Pelajaran</label><input value="IPA dan Matematika" readonly></div><div class="form-field full"><label>Alamat Sekolah</label><input value="SMP Muhammadiyah 44 Tangerang Selatan" readonly></div></div><div style="margin-top:20px;text-align:right"><button class="btn btn-primary" type="button">Simpan Perubahan</button></div></div></section><footer class="footer"><span>Sistem Presensi &amp; Manajemen Akademik SMP Muhammadiyah 44 Tangerang Selatan</span><span>© {{ date('Y') }} SMP Muhammadiyah 44 Tangerang Selatan</span></footer></main></div>
<script>window.addEventListener('load',()=>guruPage.classList.add('loaded'));function toggleSidebar(){sidebar.classList.toggle('open');sidebarOverlay.classList.toggle('show');burgerBtn.classList.toggle('active')}function updateLiveDatetime(){let n=new Date(),d=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'],m=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],p=x=>String(x).padStart(2,'0');liveDatetime.innerHTML=`<span class="date-html">${d[n.getDay()]}, ${n.getDate()} ${m[n.getMonth()]} ${n.getFullYear()}</span><span class="sep"> | </span><span class="time-html">${p(n.getHours())}:${p(n.getMinutes())}:${p(n.getSeconds())} WIB</span>`}updateLiveDatetime();setInterval(updateLiveDatetime,1000)</script>
</body></html>
